version: '3.8'

services:
  # Backend service (Spring Boot)
  backend:
    image: my-spring-app # Replace with your backend image
    ports:
      - "8081:8081"  # Map container port 8081 to host port 8081
    networks:
      - mynetwork
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Details
      SPRING_DATASOURCE_USERNAME: arz        # Admin user
      SPRING_DATASOURCE_PASSWORD: 123        # Admin password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres

  # Frontend service (React)
  frontend:
    image: react-app # Replace with your frontend image
    ports:
      - "80:80"  # Map container port 80 to host port 80
    networks:
      - mynetwork
    depends_on:
      - backend

  # PostgreSQL service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: arz
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Employee
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  # PgAdmin service
  pgadmin:
    image: dpage/pgadmin4
    container_name: ba_pgadmin1
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - mynetwork # Expose PostgreSQL port 5432 to the host

# Networks to connect all services
networks:
  mynetwork:
    driver: bridge

# Volumes for persistent PostgreSQL data
volumes:
  postgres_data: {}
  pgadmin: {}
